export const CurrentStepActionTypes = {
    FETCH_CURRENT_STEP_START: 'FETCH_CURRENT_STEP_START',
    FETCH_CURRENT_STEP_SUCCESS: 'FETCH_CURRENT_STEP_SUCCESS',
    FETCH_CURRENT_STEP_FAILURE: 'FETCH_CURRENT_STEP_FAILURE',
    COMPLETE_STEP_QUESTION_START: 'COMPLETE_STEP_QUESTION_START',
    COMPLETE_STEP_QUESTION_SUCCESS: 'COMPLETE_STEP_QUESTION_SUCCESS',
    COMPLETE_STEP_QUESTION_FAILURE: 'COMPLETE_STEP_QUESTION_FAILURE',
    COMPLETE_STEP_START: 'COMPLETE_STEP_START',
    COMPLETE_STEP_SUCCESS: 'COMPLETE_STEP_SUCCESS',
    COMPLETE_STEP_FAILURE: 'COMPLETE_STEP_FAILURE',
    DELETE_CURRENT_STEP_START: 'DELETE_CURRENT_STEP_START',
    DELETE_CURRENT_STEP_SUCCESS: 'DELETE_CURRENT_STEP_SUCCESS',
    DELETE_CURRENT_STEP_FAILURE: 'DELETE_CURRENT_STEP_FAILURE'
};