export const OrganisationActionTypes = {
    FETCH_ALL_ORGANISATIONS_START: 'FETCH_ALL_ORGANISATIONS_START',
    FETCH_ALL_ORGANISATIONS_SUCCESS: 'FETCH_ALL_ORGANISATIONS_SUCCESS',
    FETCH_ALL_ORGANISATIONS_FAILURE: 'FETCH_ALL_ORGANISATIONS_SUCCESS',
    CREATE_ORGANISATION_START: 'CREATE_ORGANISATION_START',
    CREATE_ORGANISATION_SUCCESS: 'CREATE_ORGANISATION_SUCCESS',
    CREATE_ORGANISATION_FAILURE: 'CREATE_ORGANISATION_FAILURE',
    FETCH_ORGANISATION_START: 'FETCH_ORGANISATION_START',
    FETCH_ORGANISATION_SUCCESS: 'FETCH_ORGANISATION_SUCCESS',
    FETCH_ORGANISATION_FAILURE: 'FETCH_ORGANISATION_FAILURE',
    // UPDATE_CURRENT_TASK_START: 'UPDATE_CURRENT_TASK_START',
    // UPDATE_CURRENT_TASK_SUCCESS: 'UPDATE_CURRENT_TASK_SUCCESS',
    // UPDATE_CURRENT_TASK_FAILURE: 'UPDATE_CURRENT_TASK_FAILURE',
    // DELETE_STEP: 'DELETE_STEP'
};