export const ProjectActionTypes = {
    CREATE_PROJECT_START: 'CREATE_PROJECT_START',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
    FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_SUCCESS'
};