export const CurrentPurchaseOrderActionTypes = {
    CREATE_PURCHASE_ORDER_START: 'CREATE_PURCHASE_ORDER_START',
    CREATE_PURCHASE_ORDER_SUCCESS: 'CREATE_PURCHASE_ORDER_SUCCESS',
    CREATE_PURCHASE_ORDER_FAILURE: 'CREATE_PURCHASE_ORDER_FAILURE',
};