export const CurrentPurchaseOrderActionTypes = {
    CREATE_PURCHASE_ORDER_START: 'CREATE_PURCHASE_ORDER_START',
    CREATE_PURCHASE_ORDER_SUCCESS: 'CREATE_PURCHASE_ORDER_SUCCESS',
    CREATE_PURCHASE_ORDER_FAILURE: 'CREATE_PURCHASE_ORDER_FAILURE',
    FETCH_CURRENT_PURCHASE_ORDER_START: 'FETCH_CURRENT_PURCHASE_ORDER_START',
    FETCH_CURRENT_PURCHASE_ORDER_SUCCESS: 'FETCH_CURRENT_PURCHASE_ORDER_SUCCESS',
    FETCH_CURRENT_PURCHASE_ORDER_FAILURE: 'FETCH_CURRENT_PURCHASE_ORDER_FAILURE',
    CREATE_CURRENT_PO_ITEM_START: 'CREATE_CURRENT_PO_ITEM_START',
    CREATE_CURRENT_PO_ITEM_SUCCESS: 'CREATE_CURRENT_PO_ITEM_SUCCESS',
    CREATE_CURRENT_PO_ITEM_FAILURE: 'CREATE_CURRENT_PO_ITEM_FAILURE'
};