export const CurrentTaskActionTypes = {
    FETCH_CURRENT_TASK_START: 'FETCH_CURRENT_TASK_START',
    FETCH_CURRENT_TASK_SUCCESS: 'FETCH_CURRENT_TASK_SUCCESS',
    FETCH_CURRENT_TASK_FAILURE: 'FETCH_CURRENT_TASK_SUCCESS',
    COMPLETE_CURRENT_TASK_START: 'COMPLETE_CURRENT_TASK_START',
    COMPLETE_CURRENT_TASK_SUCCESS: 'COMPLETE_CURRENT_TASK_SUCCESS',
    COMPLETE_CURRENT_TASK_FAILURE: 'COMPLETE_CURRENT_TASK_FAILURE'
};