export const CurrentTaskActionTypes = {
    FETCH_CURRENT_TASK_START: 'FETCH_CURRENT_TASK_START',
    FETCH_CURRENT_TASK_SUCCESS: 'FETCH_CURRENT_TASK_SUCCESS',
    FETCH_CURRENT_TASK_FAILURE: 'FETCH_CURRENT_TASK_SUCCESS',
    COMPLETE_CURRENT_TASK_START: 'COMPLETE_CURRENT_TASK_START',
    COMPLETE_CURRENT_TASK_SUCCESS: 'COMPLETE_CURRENT_TASK_SUCCESS',
    COMPLETE_CURRENT_TASK_FAILURE: 'COMPLETE_CURRENT_TASK_FAILURE',
    DELETE_CURRENT_TASK_START: 'DELETE_CURRENT_TASK_START',
    DELETE_CURRENT_TASK_SUCCESS: 'DELETE_CURRENT_TASK_SUCCESS',
    DELETE_CURRENT_TASK_FAILURE: 'DELETE_CURRENT_TASK_FAILURE',
    UPDATE_CURRENT_TASK_START: 'UPDATE_CURRENT_TASK_START',
    UPDATE_CURRENT_TASK_SUCCESS: 'UPDATE_CURRENT_TASK_SUCCESS',
    UPDATE_CURRENT_TASK_FAILURE: 'UPDATE_CURRENT_TASK_FAILURE',
    DELETE_STEP: 'DELETE_STEP'
};