export const CurrentChangeOrderActionTypes = {
    CREATE_CHANGE_ORDER_START: 'CREATE_CHANGE_ORDER_START',
    CREATE_CHANGE_ORDER_SUCCESS: 'CREATE_CHANGE_ORDER_SUCCESS',
    CREATE_CHANGE_ORDER_FAILURE: 'CREATE_CHANGE_ORDER_FAILURE',
    FETCH_CURRENT_CHANGE_ORDER_START: 'FETCH_CURRENT_CHANGE_ORDER_START',
    FETCH_CURRENT_CHANGE_ORDER_SUCCESS: 'FETCH_CURRENT_CHANGE_ORDER_SUCCESS',
    FETCH_CURRENT_CHANGE_ORDER_FAILURE: 'FETCH_CURRENT_CHANGE_ORDER_FAILURE',
    CREATE_CURRENT_CO_ITEM_START: 'CREATE_CURRENT_CO_ITEM_START',
    CREATE_CURRENT_CO_ITEM_SUCCESS: 'CREATE_CURRENT_CO_ITEM_SUCCESS',
    CREATE_CURRENT_CO_ITEM_FAILURE: 'CREATE_CURRENT_CO_ITEM_FAILURE'
};