export const StepActionTypes = {
    CREATE_STEP_START: 'CREATE_STEP_START',
    CREATE_STEP_SUCCESS: 'CREATE_STEP_SUCCESS',
    CREATE_STEP_FAILURE: 'CREATE_STEP_FAILURE',
    FETCH_STEPS_START: 'FETCH_STEPS_START',
    FETCH_STEPS_SUCCESS: 'FETCH_STEPS_SUCCESS',
    FETCH_STEPS_FAILURE: 'FETCH_STEPS_SUCCESS'

};