export const StepActionTypes = {
    CREATE_STEP_START: 'CREATE_STEP_START',
    CREATE_STEP_SUCCESS: 'CREATE_STEP_SUCCESS',
    CREATE_STEP_FAILURE: 'CREATE_STEP_FAILURE',
    FETCH_STEPS_START: 'FETCH_STEPS_START',
    FETCH_STEPS_SUCCESS: 'FETCH_STEPS_SUCCESS',
    FETCH_STEPS_FAILURE: 'FETCH_STEPS_SUCCESS',
    COMPLETE_STEP_QUESTION_START: 'COMPLETE_STEP_QUESTION_START',
    COMPLETE_STEP_QUESTION_SUCCESS: 'COMPLETE_STEP_QUESTION_SUCCESS',
    COMPLETE_STEP_QUESTION_FAILURE: 'COMPLETE_STEP_QUESTION_FAILURE'
};