export const CostBookActionTypes = {
    CREATE_COST_BOOK_CATEGORY_START: 'CREATE_COST_BOOK_CATEGORY_START',
    CREATE_COST_BOOK_CATEGORY_SUCCESS: 'CREATE_COST_BOOK_CATEGORY_SUCCESS',
    CREATE_COST_BOOK_CATEGORY_FAILURE: 'CREATE_COST_BOOK_CATEGORY_FAILURE',
    CREATE_COST_BOOK_COSTCODE_START: 'CREATE_COST_BOOK_COSTCODE_START',
    CREATE_COST_BOOK_COSTCODE_SUCCESS: 'CREATE_COST_BOOK_COSTCODE_SUCCESS',
    CREATE_COST_BOOK_COSTCODE_FAILURE: 'CREATE_COST_BOOK_COSTCODE_FAILURE',
    CREATE_COST_BOOK_COSTCODEITEM_START: 'CREATE_COST_BOOK_COSTCODEITEM_START',
    CREATE_COST_BOOK_COSTCODEITEM_SUCCESS: 'CREATE_COST_BOOK_COSTCODEITEM_SUCCESS',
    CREATE_COST_BOOK_COSTCODEITEM_FAILURE: 'CREATE_COST_BOOK_COSTCODEITEM_FAILURE',
    FETCH_COST_BOOK_START: 'FETCH_COST_BOOK_START',
    FETCH_COST_BOOK_SUCCESS: 'FETCH_COST_BOOK_SUCCESS',
    FETCH_COST_BOOK_FAILURE: 'FETCH_COST_BOOK_SUCCESS'
};