export const CurrentProjectActionTypes = {
    FETCH_CURRENT_PROJECT_START: 'FETCH_CURRENT_PROJECT_START',
    FETCH_CURRENT_PROJECT_SUCCESS: 'FETCH_CURRENT_PROJECT_SUCCESS',
    FETCH_CURRENT_PROJECT_FAILURE: 'FETCH_CURRENT_PROJECT_SUCCESS'
};