export const TaskActionTypes = {
  CREATE_TASK_START: "CREATE_TASK_START",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILURE: "FETCH_TASKS_SUCCESS",
  CLEAR_TASKS_DATA: "CLEAR_TASKS_DATA",
};
