export const CurrentPunchListActionTypes = {
    FETCH_CURRENT_PUNCH_LIST_START: 'FETCH_CURRENT_PUNCH_LIST_START',
    FETCH_CURRENT_PUNCH_LIST_SUCCESS: 'FETCH_CURRENT_PUNCH_LIST_SUCCESS',
    FETCH_CURRENT_PUNCH_LIST_FAILURE: 'FETCH_CURRENT_PUNCH_LIST_FAILURE',
    CREATE_PUNCH_LIST_START: 'CREATE_PUNCH_LIST_START',
    CREATE_PUNCH_LIST_SUCCESS: 'CREATE_PUNCH_LIST_SUCCESS',
    CREATE_PUNCH_LIST_FAILURE: 'CREATE_PUNCH_LIST_FAILURE',
    CREATE_PUNCH_LIST_ITEM_START: 'CREATE_PUNCH_LIST_ITEM_START',
    CREATE_PUNCH_LIST_ITEM_SUCCESS: 'CREATE_PUNCH_LIST_ITEM_SUCCESS',
    CREATE_PUNCH_LIST_ITEM_FAILURE: 'CREATE_PUNCH_LIST_ITEM_FAILURE',
};