export const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    TASK_OWNER_TRADE_PARTNER_SIGN_UP_SUCCESS: 'TASK_OWNER_TRADE_PARTNER_SIGN_UP_SUCCESS',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE: 'EMAIL_SIGN_IN_FAILURE',
    USER_SIGN_OUT: 'USER_SIGN_OUT',
    INVITE_USER_START: 'INVITE_USER_START',
    INVITE_USER_SUCCESS: 'INVITE_USER_SUCCESS',
    INVITE_USER_FAILURE: 'INVITE_USER_FAILURE'
};